services:
  frontend:
    build:
      context: ./frontend-client
    ports:
      - "5173:80"
    networks:
      - app-network

  backend:
    build:
      context: ./api-server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 12345678
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
